package org.mods.gd656killicon.common.bonus;

import org.mods.gd656killicon.common.KillType;

import java.util.List;

/**
 * 全部加分项定义（72 条）。
 *
 * <p>新增加分项 = 在此列表中添加一段 BonusDefinition.builder()...build()。
 * 必填：id（大写）、type（编号，不得与现有重复）、scoreExpression（默认倍率）、
 * displayName/description/format（至少提供 zh_cn，其余语言缺失时回退 zh_cn）。</p>
 */
public final class BonusDefinitionsArea {
    private BonusDefinitionsArea() {}

    public static List<BonusDefinition> all() {
        return List.of(
            BonusDefinition.builder()
                .id("DAMAGE").type(0).scoreExpression("1")
                .displayName("gd656killicon.bonus.DAMAGE.name")
                .description("gd656killicon.bonus.DAMAGE.desc")
                .format("造成伤害 +<score>")
                .statCategory(StatCategory.DAMAGE)
                .factor(FactorType.DAMAGE)
                .build(),
            BonusDefinition.builder()
                .id("KILL").type(1).scoreExpression("5")
                .displayName("gd656killicon.bonus.KILL.name")
                .description("gd656killicon.bonus.KILL.desc")
                .format("击杀 +<score>")
                .priorityKill(true)
                .build(),
            BonusDefinition.builder()
                .id("EXPLOSION").type(2).scoreExpression("1")
                .displayName("gd656killicon.bonus.EXPLOSION.name")
                .description("gd656killicon.bonus.EXPLOSION.desc")
                .format("爆炸伤害 +<score>")
                .statCategory(StatCategory.DAMAGE)
                .factor(FactorType.DAMAGE)
                .build(),
            BonusDefinition.builder()
                .id("HEADSHOT").type(3).scoreExpression("1")
                .displayName("gd656killicon.bonus.HEADSHOT.name")
                .description("gd656killicon.bonus.HEADSHOT.desc")
                .format("爆头伤害 +<score>")
                .statCategory(StatCategory.DAMAGE)
                .factor(FactorType.DAMAGE)
                .build(),
            BonusDefinition.builder()
                .id("CRIT").type(4).scoreExpression("1")
                .displayName("gd656killicon.bonus.CRIT.name")
                .description("gd656killicon.bonus.CRIT.desc")
                .format("暴击伤害 +<score>")
                .statCategory(StatCategory.DAMAGE)
                .factor(FactorType.DAMAGE)
                .build(),
            BonusDefinition.builder()
                .id("KILL_EXPLOSION").type(5).scoreExpression("5")
                .displayName("gd656killicon.bonus.KILL_EXPLOSION.name")
                .description("gd656killicon.bonus.KILL_EXPLOSION.desc")
                .format("爆炸击杀 +<score>")
                .priorityKill(true)
                .build(),
            BonusDefinition.builder()
                .id("KILL_HEADSHOT").type(6).scoreExpression("5")
                .displayName("gd656killicon.bonus.KILL_HEADSHOT.name")
                .description("gd656killicon.bonus.KILL_HEADSHOT.desc")
                .format("精确击败 +<score>")
                .priorityKill(true)
                .build(),
            BonusDefinition.builder()
                .id("KILL_CRIT").type(7).scoreExpression("5")
                .displayName("gd656killicon.bonus.KILL_CRIT.name")
                .description("gd656killicon.bonus.KILL_CRIT.desc")
                .format("暴击击败 +<score>")
                .priorityKill(true)
                .build(),
            BonusDefinition.builder()
                .id("KILL_COMBO").type(8).scoreExpression("8")
                .displayName("gd656killicon.bonus.KILL_COMBO.name")
                .description("gd656killicon.bonus.KILL_COMBO.desc")
                .format("<combo> 连续击败 +<score>")
                .priorityKill(true)
                .mergeBehavior(MergeBehavior.BY_COMBO)
                .factor(FactorType.COMBO)
                .streakSubtitle(2, "gd656killicon.bonus.KILL_COMBO.streak.2")
                .streakSubtitle(3, "gd656killicon.bonus.KILL_COMBO.streak.3")
                .streakSubtitle(4, "gd656killicon.bonus.KILL_COMBO.streak.4")
                .streakSubtitle(5, "gd656killicon.bonus.KILL_COMBO.streak.5")
                .streakSubtitle(6, "gd656killicon.bonus.KILL_COMBO.streak.6")
                .streakSubtitle(7, "gd656killicon.bonus.KILL_COMBO.streak.7")
                .streakSubtitle(8, "gd656killicon.bonus.KILL_COMBO.streak.8")
                .build(),
            BonusDefinition.builder()
                .id("KILL_LONG_DISTANCE").type(9).scoreExpression("1")
                .displayName("gd656killicon.bonus.KILL_LONG_DISTANCE.name")
                .description("gd656killicon.bonus.KILL_LONG_DISTANCE.desc")
                .format("远距离击败 <distance> +<score>")
                .priorityKill(true)
                .factor(FactorType.DISTANCE)
                .build(),
            BonusDefinition.builder()
                .id("KILL_INVISIBLE").type(10).scoreExpression("10")
                .displayName("gd656killicon.bonus.KILL_INVISIBLE.name")
                .description("gd656killicon.bonus.KILL_INVISIBLE.desc")
                .format("不见其人 +<score>")
                .build(),
            BonusDefinition.builder()
                .id("ASSIST").type(11).scoreExpression("1")
                .displayName("gd656killicon.bonus.ASSIST.name")
                .description("gd656killicon.bonus.ASSIST.desc")
                .format("助攻 +<score>")
                .statCategory(StatCategory.ASSIST)
                .factor(FactorType.DAMAGE)
                .build(),
            BonusDefinition.builder()
                .id("DESPERATE_COUNTERATTACK").type(12).scoreExpression("12")
                .displayName("gd656killicon.bonus.DESPERATE_COUNTERATTACK.name")
                .description("gd656killicon.bonus.DESPERATE_COUNTERATTACK.desc")
                .format("绝境反击 +<score>")
                .build(),
            BonusDefinition.builder()
                .id("AVENGE").type(13).scoreExpression("25")
                .displayName("gd656killicon.bonus.AVENGE.name")
                .description("gd656killicon.bonus.AVENGE.desc")
                .format("一雪前耻 +<score>")
                .build(),
            BonusDefinition.builder()
                .id("SHOCKWAVE").type(14).scoreExpression("20")
                .displayName("gd656killicon.bonus.SHOCKWAVE.name")
                .description("gd656killicon.bonus.SHOCKWAVE.desc")
                .format("冲击波 +<score>")
                .build(),
            BonusDefinition.builder()
                .id("BLIND_KILL").type(15).scoreExpression("12")
                .displayName("gd656killicon.bonus.BLIND_KILL.name")
                .description("gd656killicon.bonus.BLIND_KILL.desc")
                .format("无睹而中 +<score>")
                .build(),
            BonusDefinition.builder()
                .id("BUFF_KILL").type(16).scoreExpression("5")
                .displayName("gd656killicon.bonus.BUFF_KILL.name")
                .description("gd656killicon.bonus.BUFF_KILL.desc")
                .format("凭效诛敌 +<score>")
                .build(),
            BonusDefinition.builder()
                .id("DEBUFF_KILL").type(17).scoreExpression("7")
                .displayName("gd656killicon.bonus.DEBUFF_KILL.name")
                .description("gd656killicon.bonus.DEBUFF_KILL.desc")
                .format("逆效制敌 +<score>")
                .build(),
            BonusDefinition.builder()
                .id("BOTH_BUFF_DEBUFF_KILL").type(18).scoreExpression("10")
                .displayName("gd656killicon.bonus.BOTH_BUFF_DEBUFF_KILL.name")
                .description("gd656killicon.bonus.BOTH_BUFF_DEBUFF_KILL.desc")
                .format("损益同斩 +<score>")
                .build(),
            BonusDefinition.builder()
                .id("LAST_BULLET_KILL").type(19).scoreExpression("30")
                .displayName("gd656killicon.bonus.LAST_BULLET_KILL.name")
                .description("gd656killicon.bonus.LAST_BULLET_KILL.desc")
                .format("末弹酬勇 +<score>")
                .build(),
            BonusDefinition.builder()
                .id("ONE_BULLET_MULTI_KILL").type(20).scoreExpression("8")
                .displayName("gd656killicon.bonus.ONE_BULLET_MULTI_KILL.name")
                .description("gd656killicon.bonus.ONE_BULLET_MULTI_KILL.desc")
                .format("一箭<multi_kill>雕 +<score>")
                .factor(FactorType.COUNT)
                .build(),
            BonusDefinition.builder()
                .id("EFFORTLESS_KILL").type(21).scoreExpression("8")
                .displayName("gd656killicon.bonus.EFFORTLESS_KILL.name")
                .description("gd656killicon.bonus.EFFORTLESS_KILL.desc")
                .format("游刃有余 +<score>")
                .build(),
            BonusDefinition.builder()
                .id("BACKSTAB_KILL").type(22).scoreExpression("8")
                .displayName("gd656killicon.bonus.BACKSTAB_KILL.name")
                .description("gd656killicon.bonus.BACKSTAB_KILL.desc")
                .format("背袭 +<score>")
                .build(),
            BonusDefinition.builder()
                .id("BACKSTAB_MELEE_KILL").type(23).scoreExpression("15")
                .displayName("gd656killicon.bonus.BACKSTAB_MELEE_KILL.name")
                .description("gd656killicon.bonus.BACKSTAB_MELEE_KILL.desc")
                .format("背刺 +<score>")
                .build(),
            BonusDefinition.builder()
                .id("BRAVE_RETURN").type(24).scoreExpression("12")
                .displayName("gd656killicon.bonus.BRAVE_RETURN.name")
                .description("gd656killicon.bonus.BRAVE_RETURN.desc")
                .format("勇者归来 +<score>")
                .build(),
            BonusDefinition.builder()
                .id("JUSTICE_FROM_ABOVE").type(25).scoreExpression("10")
                .displayName("gd656killicon.bonus.JUSTICE_FROM_ABOVE.name")
                .description("gd656killicon.bonus.JUSTICE_FROM_ABOVE.desc")
                .format("天降正义 +<score>")
                .build(),
            BonusDefinition.builder()
                .id("ABSOLUTE_AIR_CONTROL").type(26).scoreExpression("20")
                .displayName("gd656killicon.bonus.ABSOLUTE_AIR_CONTROL.name")
                .description("gd656killicon.bonus.ABSOLUTE_AIR_CONTROL.desc")
                .format("绝对制空权 +<score>")
                .build(),
            BonusDefinition.builder()
                .id("BERSERKER").type(27).scoreExpression("3")
                .displayName("gd656killicon.bonus.BERSERKER.name")
                .description("gd656killicon.bonus.BERSERKER.desc")
                .format("狂战士 +<score>")
                .build(),
            BonusDefinition.builder()
                .id("INTERRUPTED_STREAK").type(28).scoreExpression("6")
                .displayName("gd656killicon.bonus.INTERRUPTED_STREAK.name")
                .description("gd656killicon.bonus.INTERRUPTED_STREAK.desc")
                .format("已中止敌方 <streak> 连杀 +<score>")
                .factor(FactorType.STREAK)
                .build(),
            BonusDefinition.builder()
                .id("LEAVE_IT_TO_ME").type(29).scoreExpression("20")
                .displayName("gd656killicon.bonus.LEAVE_IT_TO_ME.name")
                .description("gd656killicon.bonus.LEAVE_IT_TO_ME.desc")
                .format("交给我 +<score>")
                .build(),
            BonusDefinition.builder()
                .id("SAVIOR").type(30).scoreExpression("10")
                .displayName("gd656killicon.bonus.SAVIOR.name")
                .description("gd656killicon.bonus.SAVIOR.desc")
                .format("救星 +<score>")
                .build(),
            BonusDefinition.builder()
                .id("SLAY_THE_LEADER").type(31).scoreExpression("18")
                .displayName("gd656killicon.bonus.SLAY_THE_LEADER.name")
                .description("gd656killicon.bonus.SLAY_THE_LEADER.desc")
                .format("枪打出头鸟 +<score>")
                .build(),
            BonusDefinition.builder()
                .id("PURGE").type(32).scoreExpression("30")
                .displayName("gd656killicon.bonus.PURGE.name")
                .description("gd656killicon.bonus.PURGE.desc")
                .format("肃清 +<score>")
                .build(),
            BonusDefinition.builder()
                .id("QUICK_SWITCH").type(33).scoreExpression("3")
                .displayName("gd656killicon.bonus.QUICK_SWITCH.name")
                .description("gd656killicon.bonus.QUICK_SWITCH.desc")
                .format("切枪制人 +<score>")
                .build(),
            BonusDefinition.builder()
                .id("SEIZE_OPPORTUNITY").type(34).scoreExpression("5")
                .displayName("gd656killicon.bonus.SEIZE_OPPORTUNITY.name")
                .description("gd656killicon.bonus.SEIZE_OPPORTUNITY.desc")
                .format("机不可失 +<score>")
                .build(),
            BonusDefinition.builder()
                .id("BLOODTHIRSTY").type(35).scoreExpression("5")
                .displayName("gd656killicon.bonus.BLOODTHIRSTY.name")
                .description("gd656killicon.bonus.BLOODTHIRSTY.desc")
                .format("嗜血 +<score>")
                .build(),
            BonusDefinition.builder()
                .id("MERCILESS").type(36).scoreExpression("10")
                .displayName("gd656killicon.bonus.MERCILESS.name")
                .description("gd656killicon.bonus.MERCILESS.desc")
                .format("无情 +<score>")
                .build(),
            BonusDefinition.builder()
                .id("VALIANT").type(37).scoreExpression("15")
                .displayName("gd656killicon.bonus.VALIANT.name")
                .description("gd656killicon.bonus.VALIANT.desc")
                .format("勇猛 +<score>")
                .build(),
            BonusDefinition.builder()
                .id("FIERCE").type(38).scoreExpression("20")
                .displayName("gd656killicon.bonus.FIERCE.name")
                .description("gd656killicon.bonus.FIERCE.desc")
                .format("凶狠 +<score>")
                .build(),
            BonusDefinition.builder()
                .id("SAVAGE").type(39).scoreExpression("25")
                .displayName("gd656killicon.bonus.SAVAGE.name")
                .description("gd656killicon.bonus.SAVAGE.desc")
                .format("野蛮 +<score>")
                .build(),
            BonusDefinition.builder()
                .id("POTATO_AIM").type(40).scoreExpression("5")
                .displayName("gd656killicon.bonus.POTATO_AIM.name")
                .description("gd656killicon.bonus.POTATO_AIM.desc")
                .format("马枪怪 +<score>")
                .build(),
            BonusDefinition.builder()
                .id("HIT_VEHICLE_ARMOR").type(41).scoreExpression("1.5")
                .displayName("gd656killicon.bonus.HIT_VEHICLE_ARMOR.name")
                .description("gd656killicon.bonus.HIT_VEHICLE_ARMOR.desc")
                .format("命中装甲 +<score>")
                .build(),
            BonusDefinition.builder()
                .id("DESTROY_VEHICLE").type(42).scoreExpression("1.5")
                .displayName("gd656killicon.bonus.DESTROY_VEHICLE.name")
                .description("gd656killicon.bonus.DESTROY_VEHICLE.desc")
                .format("摧毁装甲 +<score>")
                .factor(FactorType.SCORE)
                .build(),
            BonusDefinition.builder()
                .id("VEHICLE_REPAIR").type(43).scoreExpression("10")
                .displayName("gd656killicon.bonus.VEHICLE_REPAIR.name")
                .description("gd656killicon.bonus.VEHICLE_REPAIR.desc")
                .format("载具修理 +<score>")
                .build(),
            BonusDefinition.builder()
                .id("VALUE_TARGET_DESTROYED").type(44).scoreExpression("1")
                .displayName("gd656killicon.bonus.VALUE_TARGET_DESTROYED.name")
                .description("gd656killicon.bonus.VALUE_TARGET_DESTROYED.desc")
                .format("价值目标摧毁 +<score>")
                .scoreCap(2000f)
                .factor(FactorType.DAMAGE)
                .build(),
            BonusDefinition.builder()
                .id("LOCKED_TARGET").type(45).scoreExpression("12")
                .displayName("gd656killicon.bonus.LOCKED_TARGET.name")
                .description("gd656killicon.bonus.LOCKED_TARGET.desc")
                .format("锁定目标 +<score>")
                .build(),
            BonusDefinition.builder()
                .id("HOLD_POSITION").type(46).scoreExpression("10")
                .displayName("gd656killicon.bonus.HOLD_POSITION.name")
                .description("gd656killicon.bonus.HOLD_POSITION.desc")
                .format("坚守阵地 +<score>")
                .build(),
            BonusDefinition.builder()
                .id("CHARGE_ASSAULT").type(47).scoreExpression("15")
                .displayName("gd656killicon.bonus.CHARGE_ASSAULT.name")
                .description("gd656killicon.bonus.CHARGE_ASSAULT.desc")
                .format("冲锋陷阵 +<score>")
                .build(),
            BonusDefinition.builder()
                .id("FIRE_SUPPRESSION").type(48).scoreExpression("15")
                .displayName("gd656killicon.bonus.FIRE_SUPPRESSION.name")
                .description("gd656killicon.bonus.FIRE_SUPPRESSION.desc")
                .format("火力压制 +<score>")
                .build(),
            BonusDefinition.builder()
                .id("DESTROY_BLOCK").type(49).scoreExpression("1")
                .displayName("gd656killicon.bonus.DESTROY_BLOCK.name")
                .description("gd656killicon.bonus.DESTROY_BLOCK.desc")
                .format("摧毁道具 +<score>")
                .disabledByDefault(true)
                .build(),
            BonusDefinition.builder()
                .id("SPOTTING").type(50).scoreExpression("5")
                .displayName("gd656killicon.bonus.SPOTTING.name")
                .description("gd656killicon.bonus.SPOTTING.desc")
                .format("索敌 +<score>")
                .build(),
            BonusDefinition.builder()
                .id("SPOTTING_KILL").type(51).scoreExpression("30")
                .displayName("gd656killicon.bonus.SPOTTING_KILL.name")
                .description("gd656killicon.bonus.SPOTTING_KILL.desc")
                .format("标记击杀 +<score>")
                .build(),
            BonusDefinition.builder()
                .id("SPOTTING_TEAM_ASSIST").type(52).scoreExpression("15")
                .displayName("gd656killicon.bonus.SPOTTING_TEAM_ASSIST.name")
                .description("gd656killicon.bonus.SPOTTING_TEAM_ASSIST.desc")
                .format("标记小队助攻 +<score>")
                .build(),
            BonusDefinition.builder()
                .id("CONQUEST_CAPTURE_PROGRESS").type(53).scoreExpression("2")
                .displayName("gd656killicon.bonus.CONQUEST_CAPTURE_PROGRESS.name")
                .description("gd656killicon.bonus.CONQUEST_CAPTURE_PROGRESS.desc")
                .format("进度占领据点 +<score>")
                .build(),
            BonusDefinition.builder()
                .id("CONQUEST_CAPTURE_NEUTRALIZE").type(54).scoreExpression("10")
                .displayName("gd656killicon.bonus.CONQUEST_CAPTURE_NEUTRALIZE.name")
                .description("gd656killicon.bonus.CONQUEST_CAPTURE_NEUTRALIZE.desc")
                .format("中和据点 +<score>")
                .build(),
            BonusDefinition.builder()
                .id("CONQUEST_CAPTURE_CONTROL").type(55).scoreExpression("20")
                .displayName("gd656killicon.bonus.CONQUEST_CAPTURE_CONTROL.name")
                .description("gd656killicon.bonus.CONQUEST_CAPTURE_CONTROL.desc")
                .format("控制目标据点 +<score>")
                .build(),
            BonusDefinition.builder()
                .id("SQUAD_DEPLOY_ON_YOU").type(56).scoreExpression("10")
                .displayName("gd656killicon.bonus.SQUAD_DEPLOY_ON_YOU.name")
                .description("gd656killicon.bonus.SQUAD_DEPLOY_ON_YOU.desc")
                .format("小队在你的位置部署 +<score>")
                .build(),
            BonusDefinition.builder()
                .id("SQUAD_LAST_MEMBER_KILL").type(57).scoreExpression("15")
                .displayName("gd656killicon.bonus.SQUAD_LAST_MEMBER_KILL.name")
                .description("gd656killicon.bonus.SQUAD_LAST_MEMBER_KILL.desc")
                .format("孤身奋战 +<score>")
                .build(),
            BonusDefinition.builder()
                .id("EMERGENCY_REINFORCEMENT").type(58).scoreExpression("20")
                .displayName("gd656killicon.bonus.EMERGENCY_REINFORCEMENT.name")
                .description("gd656killicon.bonus.EMERGENCY_REINFORCEMENT.desc")
                .format("价值小队部署 +<score>")
                .build(),
            BonusDefinition.builder()
                .id("SQUAD_WIPE_COMPLETION").type(59).scoreExpression("40")
                .displayName("gd656killicon.bonus.SQUAD_WIPE_COMPLETION.name")
                .description("gd656killicon.bonus.SQUAD_WIPE_COMPLETION.desc")
                .format("完成小队团灭 +<score>")
                .build(),
            BonusDefinition.builder()
                .id("TACTICAL_GADGET_DESTROYED").type(60).scoreExpression("20")
                .displayName("gd656killicon.bonus.TACTICAL_GADGET_DESTROYED.name")
                .description("gd656killicon.bonus.TACTICAL_GADGET_DESTROYED.desc")
                .format("摧毁战术道具 +<score>")
                .build(),
            BonusDefinition.builder()
                .id("SQUAD_BEACON_DEPLOY").type(61).scoreExpression("20")
                .displayName("gd656killicon.bonus.SQUAD_BEACON_DEPLOY.name")
                .description("gd656killicon.bonus.SQUAD_BEACON_DEPLOY.desc")
                .format("小队重生信标部署 +<score>")
                .build(),
            BonusDefinition.builder()
                .id("VALUE_OBJECTIVE_SUPPORT_BEACON_DEPLOY").type(62).scoreExpression("5")
                .displayName("gd656killicon.bonus.VALUE_OBJECTIVE_SUPPORT_BEACON_DEPLOY.name")
                .description("gd656killicon.bonus.VALUE_OBJECTIVE_SUPPORT_BEACON_DEPLOY.desc")
                .format("价值阵地支援信标部署 +<score>")
                .build(),
            BonusDefinition.builder()
                .id("HEALING").type(63).scoreExpression("10")
                .displayName("gd656killicon.bonus.HEALING.name")
                .description("gd656killicon.bonus.HEALING.desc")
                .format("治疗 +<score>")
                .build(),
            BonusDefinition.builder()
                .id("AMMO_SUPPLY").type(64).scoreExpression("10")
                .displayName("gd656killicon.bonus.AMMO_SUPPLY.name")
                .description("gd656killicon.bonus.AMMO_SUPPLY.desc")
                .format("弹药补给 +<score>")
                .build(),
            BonusDefinition.builder()
                .id("REVIVE").type(65).scoreExpression("100")
                .displayName("gd656killicon.bonus.REVIVE.name")
                .description("gd656killicon.bonus.REVIVE.desc")
                .format("急救 +<score>")
                .iconKillType(KillType.MEDIC)
                .statCategory(StatCategory.REVIVE)
                .build(),
            BonusDefinition.builder()
                .id("VEHICLE_DESTROY_ASSIST").type(66).scoreExpression("1")
                .displayName("gd656killicon.bonus.VEHICLE_DESTROY_ASSIST.name")
                .description("gd656killicon.bonus.VEHICLE_DESTROY_ASSIST.desc")
                .format("载具摧毁助攻 +<score>")
                .iconKillType(KillType.VEHICLE_DESTROY_ASSIST)
                .factor(FactorType.DAMAGE)
                .build(),
            BonusDefinition.builder()
                .id("FRIENDLY_DEPLOY_ON_YOUR_VEHICLE").type(67).scoreExpression("10")
                .displayName("gd656killicon.bonus.FRIENDLY_DEPLOY_ON_YOUR_VEHICLE.name")
                .description("gd656killicon.bonus.FRIENDLY_DEPLOY_ON_YOUR_VEHICLE.desc")
                .format("友军部署到你的载具 +<score>")
                .build(),
            BonusDefinition.builder()
                .id("GROUND_SENSOR_SCAN").type(68).scoreExpression("5")
                .displayName("gd656killicon.bonus.GROUND_SENSOR_SCAN.name")
                .description("gd656killicon.bonus.GROUND_SENSOR_SCAN.desc")
                .format("扫描敌军 +<score>")
                .build(),
            BonusDefinition.builder()
                .id("RUSH_BOMB_DEFUSED").type(69).scoreExpression("200")
                .displayName("gd656killicon.bonus.RUSH_BOMB_DEFUSED.name")
                .description("gd656killicon.bonus.RUSH_BOMB_DEFUSED.desc")
                .format("拆除炸弹 +<score>")
                .killFeedPayload("rush_bomb_defused")
                .build(),
            BonusDefinition.builder()
                .id("RUSH_BOMB_PLANTED").type(70).scoreExpression("200")
                .displayName("gd656killicon.bonus.RUSH_BOMB_PLANTED.name")
                .description("gd656killicon.bonus.RUSH_BOMB_PLANTED.desc")
                .format("安装炸弹 +<score>")
                .killFeedPayload("rush_bomb_planted")
                .build(),
            BonusDefinition.builder()
                .id("RUSH_OBJECTIVE_DESTROYED").type(71).scoreExpression("500")
                .displayName("gd656killicon.bonus.RUSH_OBJECTIVE_DESTROYED.name")
                .description("gd656killicon.bonus.RUSH_OBJECTIVE_DESTROYED.desc")
                .format("炸毁通讯设施 +<score>")
                .build()
        );
    }
}
